# کانفیگ لوکال Redis برای توسعه روی ویندوز
# اجرا:
#   "C:\Program Files\Redis\redis-server.exe" redis.local.conf

include C:\\Program Files\\Redis\\redis.windows.conf

dir C:\\Users\\Asus\\AppData\\Local\\RedisData
dbfilename dump.rdb
stop-writes-on-bgsave-error no
