# Generated by Django 5.2.16 on 2026-07-28 21:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('period_unit', models.CharField(choices=[('day', 'روز'), ('week', 'هفته'), ('month', 'ماه')], default='week', max_length=10, verbose_name='واحد زمان')),
                ('duration', models.PositiveIntegerField(default=1, help_text='تعداد واحد زمانی (مثلاً ۳ هفته)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت')),
                ('starts_on', models.DateField(verbose_name='تاریخ شروع')),
                ('ends_on', models.DateField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی\u200cشده'), ('active', 'فعال'), ('completed', 'تمام\u200cشده'), ('failed', 'ناتمام'), ('cancelled', 'لغو\u200cشده')], db_index=True, default='planned', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'چالش',
                'verbose_name_plural': 'چالش\u200cها',
                'ordering': ['-starts_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_pages', models.PositiveIntegerField(blank=True, help_text='اختیاری — برای نسخه\u200cهای بعدی', null=True, verbose_name='هدف صفحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_links', to='books.book', verbose_name='کتاب')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_books', to='challenges.challenge', verbose_name='چالش')),
            ],
            options={
                'verbose_name': 'کتاب چالش',
                'verbose_name_plural': 'کتاب\u200cهای چالش',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='books',
            field=models.ManyToManyField(related_name='challenges', through='challenges.ChallengeBook', to='books.book', verbose_name='کتاب\u200cها'),
        ),
        migrations.AddConstraint(
            model_name='challengebook',
            constraint=models.UniqueConstraint(fields=('challenge', 'book'), name='unique_challenge_book'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['owner', 'status'], name='challenges__owner_i_0f6bbd_idx'),
        ),
    ]
