# Generated by Django 5.2.7 on 2026-07-23 21:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('author', models.CharField(max_length=255, verbose_name='نویسنده')),
                ('total_pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد صفحات')),
                ('current_page', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صفحه فعلی')),
                ('status', models.CharField(choices=[('want_to_read', 'می\u200cخواهم بخوانم'), ('reading', 'در حال خواندن'), ('paused', 'متوقف شده'), ('finished', 'تمام شده'), ('abandoned', 'رها شده')], db_index=True, default='want_to_read', max_length=20, verbose_name='وضعیت')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='جلد کتاب')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت کلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('text', 'متن'), ('voice', 'ویس'), ('image', 'تصویر')], default='text', max_length=10, verbose_name='نوع محتوا')),
                ('kind', models.CharField(choices=[('viewpoint', 'دیدگاه'), ('feeling', 'حس'), ('book_text', 'متن کتاب')], db_index=True, default='viewpoint', max_length=20, verbose_name='نوع دیدگاه')),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره صفحه')),
                ('text_content', models.TextField(blank=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/entries/images/', verbose_name='تصویر')),
                ('audio', models.FileField(blank=True, null=True, upload_to='books/entries/audio/', verbose_name='فایل صوتی')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'یادداشت',
                'verbose_name_plural': 'یادداشت\u200cها',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['book', 'page_number'], name='books_entry_book_id_c7825f_idx'), models.Index(fields=['book', 'kind'], name='books_entry_book_id_5e86ed_idx')],
            },
        ),
    ]
