# Generated by Django 5.2.7 on 2026-07-31 21:50

from django.conf import settings
from django.db import migrations, models


def fingerprint(value: str) -> str:
    import re
    import unicodedata

    if not value:
        return ''
    char_map = str.maketrans({
        'ي': 'ی',
        'ى': 'ی',
        'ك': 'ک',
        'ة': 'ه',
        'ۀ': 'ه',
        'ھ': 'ه',
        'ە': 'ه',
        'ؤ': 'و',
        'إ': 'ا',
        'أ': 'ا',
        'ٱ': 'ا',
    })
    invisible = dict.fromkeys(map(ord, '\u200c\u200d\u200e\u200f\ufeff\u00a0'), None)
    text = unicodedata.normalize('NFKC', str(value)).strip()
    text = text.translate(char_map).translate(invisible).replace('\u0640', '')
    text = ''.join(ch for ch in text if unicodedata.category(ch) != 'Mn')
    text = text.casefold()
    text = re.sub(r'[^\w\s]', ' ', text, flags=re.UNICODE)
    text = re.sub(r'\s+', ' ', text).strip().replace(' ', '')
    return text


def populate_normalized(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.all().iterator():
        book.title_normalized = fingerprint(book.title)
        book.author_normalized = fingerprint(book.author)
        book.save(update_fields=['title_normalized', 'author_normalized'])

    # Resolve accidental duplicates so unique constraint can apply
    seen = {}
    for book in Book.objects.all().order_by('owner_id', 'id'):
        key = (book.owner_id, book.title_normalized, book.author_normalized)
        if key not in seen:
            seen[key] = 1
            continue
        seen[key] += 1
        suffix = f' #{seen[key]}'
        book.title = f'{book.title}{suffix}'
        book.title_normalized = fingerprint(book.title)
        book.save(update_fields=['title', 'title_normalized'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_normalized',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                editable=False,
                max_length=255,
                verbose_name='نویسنده نرمال',
            ),
        ),
        migrations.AddField(
            model_name='book',
            name='title_normalized',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                editable=False,
                max_length=255,
                verbose_name='عنوان نرمال',
            ),
        ),
        migrations.RunPython(populate_normalized, noop_reverse),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(
                fields=['owner', 'title_normalized', 'author_normalized'],
                name='books_book_owner_i_7c1db3_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(
                fields=('owner', 'title_normalized', 'author_normalized'),
                name='books_unique_owner_title_author_norm',
            ),
        ),
    ]
