# Generated by Django 5.2.7 on 2026-07-31 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='واژه')),
                ('meaning', models.TextField(verbose_name='معنی')),
                ('usage', models.TextField(blank=True, verbose_name='کاربرد در جمله')),
                ('audio', models.FileField(blank=True, null=True, upload_to='vocabulary/audio/', verbose_name='تلفظ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'واژه',
                'verbose_name_plural': 'واژه\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='vocabulary__owner_i_80f54f_idx')],
            },
        ),
    ]
